### ISSUE TITLE
qr-filetransfer/main.go:93: srv.Shutdown undefined 

### ISSUE THREAD

**Issue by anxiaokai** [claudiodangelis/qr-filetransfer#64]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [x] I have a question
- [ ] Other

it display this 
__gotest go get github.com/claudiodangelis/qr-filetransfer
github.com/claudiodangelis/qr-filetransfer
src/github.com/claudiodangelis/qr-filetransfer/main.go:93: srv.Shutdown undefined (type *http.Server has no field or method Shutdown)
src/github.com/claudiodangelis/qr-filetransfer/main.go:163: undefined: http.ErrServerClosed__
when i go get it.

I do not know what happen,beacuse i know few for golang.

- My Go version is: _(version go1.7beta1 darwin/amd64)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(/Users/sunxiaokai/gotest)_

**Comment by claudiodangelis** [comment]
Hello @anxiaokai, thanks for reporting, the problem is that your Go version is outdated, please upgrade Golang then try again, the current stable version is go1.10.2 (but it will probably work with go1.8 as well).

I realize there is no indication of this constraint in the README, I will fix that soon.

Thank you!
